---
# ArgoCD Application: Predictive Inference
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-predictive
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kserve-gitops-blueprint
    app.kubernetes.io/component: inference-predictive
spec:
  project: kserve-gitops-blueprint
  source:
    repoURL: 'https://github.com/AymenSegni/kserve-gitops-blueprint.git'
    targetRevision: main
    path: kserve/predictive
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ml-predictive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
