# Sentence-BERT: Predictive InferenceService
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sentence-bert
  namespace: ml-predictive
  annotations:
    autoscaling.knative.dev/min-scale: "0"
    autoscaling.knative.dev/max-scale: "3"
    autoscaling.knative.dev/target: "20" # High concurrency text embeddings
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    containers:
      - name: kserve-container
        image: ghcr.io/aymensegni/sentence-bert-server:v1
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: MODEL_NAME
            value: sentence-bert
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /v2/health/ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v2/health/live
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
